// <auto-generated />
using System;
using Laboratory.Services.TestParameterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laboratory.Services.TestParameterAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403084615_AddNewTestDetails")]
    partial class AddNewTestDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Laboratory.Services.TestParameterAPI.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<double?>("Albumin")
                        .HasColumnType("float");

                    b.Property<double?>("AlkalinePhosphatase")
                        .HasColumnType("float");

                    b.Property<double?>("Basophils")
                        .HasColumnType("float");

                    b.Property<double?>("CReactiveProtein")
                        .HasColumnType("float");

                    b.Property<string>("Casts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CholHDLRatio")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("CollectedDate")
                        .HasColumnType("date");

                    b.Property<double?>("ControlTime")
                        .HasColumnType("float");

                    b.Property<string>("Crystals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<double?>("DirectBilirubin")
                        .HasColumnType("float");

                    b.Property<double?>("ESR")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Eosinophils")
                        .HasColumnType("float");

                    b.Property<string>("EpithelialCells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FBS")
                        .HasColumnType("float");

                    b.Property<string>("FBS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FBS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FBSADGW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GFR")
                        .HasColumnType("float");

                    b.Property<double?>("GGT")
                        .HasColumnType("float");

                    b.Property<double?>("GTT_1stHour")
                        .HasColumnType("float");

                    b.Property<double?>("GTT_2ndHour")
                        .HasColumnType("float");

                    b.Property<double?>("Globulin")
                        .HasColumnType("float");

                    b.Property<double?>("GranAbsolute")
                        .HasColumnType("float");

                    b.Property<double?>("GranPercent")
                        .HasColumnType("float");

                    b.Property<double?>("HCT")
                        .HasColumnType("float");

                    b.Property<double?>("HDL")
                        .HasColumnType("float");

                    b.Property<string>("HGB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Hemoglobin")
                        .HasColumnType("float");

                    b.Property<double?>("INR")
                        .HasColumnType("float");

                    b.Property<double?>("IndirectBilirubin")
                        .HasColumnType("float");

                    b.Property<bool?>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<string>("KetoneBodies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LDL")
                        .HasColumnType("float");

                    b.Property<int?>("LabNumber")
                        .HasColumnType("int");

                    b.Property<double?>("LymphAbsolute")
                        .HasColumnType("float");

                    b.Property<double?>("LymphPercent")
                        .HasColumnType("float");

                    b.Property<double?>("Lymphocytes")
                        .HasColumnType("float");

                    b.Property<double?>("MCH")
                        .HasColumnType("float");

                    b.Property<double?>("MCHC")
                        .HasColumnType("float");

                    b.Property<double?>("MCV")
                        .HasColumnType("float");

                    b.Property<double?>("MIDAbsolute")
                        .HasColumnType("float");

                    b.Property<double?>("MIDPercent")
                        .HasColumnType("float");

                    b.Property<double?>("MPV")
                        .HasColumnType("float");

                    b.Property<double?>("Monocytes")
                        .HasColumnType("float");

                    b.Property<string>("Mucous")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Neutrophils")
                        .HasColumnType("float");

                    b.Property<double?>("NonHDLChol")
                        .HasColumnType("float");

                    b.Property<string>("Organisms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PCT")
                        .HasColumnType("float");

                    b.Property<double?>("PCV")
                        .HasColumnType("float");

                    b.Property<double?>("PDW")
                        .HasColumnType("float");

                    b.Property<double?>("PLT")
                        .HasColumnType("float");

                    b.Property<string>("PPBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PPBS")
                        .HasColumnType("float");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PlateletCount")
                        .HasColumnType("float");

                    b.Property<double?>("PostBreakfast")
                        .HasColumnType("float");

                    b.Property<double?>("PostDinner")
                        .HasColumnType("float");

                    b.Property<double?>("PostLunch")
                        .HasColumnType("float");

                    b.Property<double?>("Potassium")
                        .HasColumnType("float");

                    b.Property<double?>("ProthrombinTime")
                        .HasColumnType("float");

                    b.Property<string>("PusCells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RBC")
                        .HasColumnType("float");

                    b.Property<double?>("RBS")
                        .HasColumnType("float");

                    b.Property<double?>("RDW_CV")
                        .HasColumnType("float");

                    b.Property<double?>("RDW_SD")
                        .HasColumnType("float");

                    b.Property<string>("Reaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("RedCells")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReducingSubstances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReportedDate")
                        .HasColumnType("date");

                    b.Property<double?>("SGOT")
                        .HasColumnType("float");

                    b.Property<double?>("SGPT")
                        .HasColumnType("float");

                    b.Property<double?>("SerumCalcium")
                        .HasColumnType("float");

                    b.Property<double?>("SerumCreatinine")
                        .HasColumnType("float");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("SpecificGravity")
                        .HasColumnType("float");

                    b.Property<string>("TestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalBilirubin")
                        .HasColumnType("float");

                    b.Property<double?>("TotalCholesterol")
                        .HasColumnType("float");

                    b.Property<double?>("TotalProtein")
                        .HasColumnType("float");

                    b.Property<string>("Transparency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Triglycerides")
                        .HasColumnType("float");

                    b.Property<string>("UrineBilirubin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrineColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrineProtein")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urobilinogen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VLDL")
                        .HasColumnType("float");

                    b.Property<double?>("WBC")
                        .HasColumnType("float");

                    b.Property<string>("YeastCells")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
